[project]
name = "django-diploma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[gevent]>=5.4.0",
    "django==5.0",
    "django-cleanup>=9.0.0",
    "docutils>=0.21.2",
    "openpyxl>=3.1.5",
    "pillow>=11.1.0",
    "python-dotenv>=1.0.1",
    "redis>=5.2.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
]
