"""
Django settings for online_store project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

from django.conf.global_settings import SERVER_EMAIL
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _




load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #
    'profiles.apps.ProfilesConfig',
    'shop.apps.ShopConfig',
    'django_cleanup',
    'banners.apps.BannersConfig',
    'reviews.apps.ReviewsConfig',
    'comparison.apps.ComparisonConfig',
    'viewed_products.apps.ViewedProductsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'online_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / ".." / "templates",
            BASE_DIR / "reviews" / "templates" / "reviews",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'online_store.context_processors.category_menu'
            ],
        },
    },
]

WSGI_APPLICATION = 'online_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'profiles.User'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', _("English")),
    ('ru', _("Russian"))
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

LOCALE_PATHS = [
    BASE_DIR / 'locale/'
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / '..' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / '..' / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGOUT_REDIRECT_URL = '/'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("SMTP_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "0") == "1"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "1") == "1"
EMAIL_HOST_USER = os.getenv("EMAIL", "your email")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD", 'your password')

ADMIN_EMAILS = os.getenv("ADMIN_EMAILS", "").split(",")

DEFAULT_LIMIT_REVIEWS = 5

# redis
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", 6379)
REDIS_LOGS_DB = int(os.getenv("REDIS_LOGS_DB", 0))  # db for celery logs

# logging
LOGLEVEL = os.getenv("DJANGO_LOGLEVEL", "debug").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "base": {
            "format": "[%(levelname)s] [%(asctime)s] [%(name)s] %(funcName)s | %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": LOGLEVEL,
            "formatter": "base",
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "level": LOGLEVEL,
            "formatter": "base",
            "filename": "server_logfile.log",
            "backupCount": 3,
            "when": "d",
            "interval": 10,
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "main": {
            "level": LOGLEVEL,
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "tasks": {
            "level": LOGLEVEL,
            "handlers": ["console", "file"],
            "propagate": False
        }
    },
}

# celery
CELERY_ACCEPT_CONTENT = os.getenv("CELERY_ACCEPT_CONTENT", "json").split(",")
CELERY_RESULT_ACCEPT_CONTENT = os.getenv("CELERY_RESULT_ACCEPT_CONTENT", "json").split(",")
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", 300))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", 120))
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost")
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost")
CELERY_CONCURRENCY = int(os.getenv("CELERY_CONCURRENCY", 4))

# import_data command settings
DIR_WITH_IMPORT_FILES = os.getenv("DIR_WITH_IMPORT_FILES", str(BASE_DIR / ".." / "media" / "import_files"))
DIR_WITH_SUCCESSFUL_IMPORTS = os.getenv("DIR_WITH_SUCCESSFUL_IMPORTS", str(BASE_DIR / ".." / "successful_imports"))
DIR_WITH_IMPORTS_WITH_ERRORS = os.getenv("DIR_WITH_IMPORTS_WITH_ERRORS", str(BASE_DIR / ".." / "imports_with_errors"))
